version: '3'
services:
  db:
    image: "postgres:10.4"
    ports:
      - "54330:5433"
    volumes:
      - "../../postgres:/var/lib/postgresql/data"
    # logging:
    #   driver: none # this disables logs!nv
    restart: unless-stopped
  web:
    build: ../../
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: ../../
    command: 'bundle exec sidekiq'
    volumes:
      - ../../:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis