version: '3'
services:
  db:
    image: "postgres:10.4"
    ports:
      - "54320:5432"
    volumes:
      - "../../postgres:/var/lib/postgresql/data"
    # logging:
    #   driver: none # this disables logs!nv
    restart: unless-stopped
  web:
    build: ../../
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db